edit_uri: ''
extra_css:
- css/extra.css
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
google_analytics:
- UA-27795084-5
- mkdocs.org
markdown_extensions:
- toc:
    separator: '#'
- admonition
- def_list
- mdx_gh_links:
    repo: mkdocs
    user: mkdocs
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
nav:
- Home: index.md
- Books:
  - Introduction: Books/index.md
- Data-structure:
  - Generic-double-linked-list:
    - Introduction: Data-structure/Generic-double-linked-list/index.md
  - Rax:
    - Introduction: Data-structure/Rax/index.md
  - Dict:
    - Introduction: Data-structure/Dict/index.md
    - Dict-usage: Data-structure/Dict/Dict-usage.md
    - Incremental-rehash:
      - Introduction: Data-structure/Dict/Incremental-rehash/index.md
- Event-library:
  - Introduction: Event-library/index.md
  - Redis-event-library-office-doc:
    - Introduction: Event-library/Redis-event-library-office-doc/index.md
  - Low-level-IO-multiplex:
    - Introduction: Event-library/Low-level-IO-multiplex/index.md
  - High-level:
    - Introduction: Event-library/High-level/index.md
- Sentinel:
  - Redis-Sentinel: Sentinel/Redis-Sentinel.md
- Command:
  - Commands: Command/Commands.md
- Clients:
  - Redis-plus-plus:
    - Redis-plus-plus: Clients/Redis-plus-plus/Redis-plus-plus.md
- Redis-cli:
  - Redis-cli: Redis-cli/Redis-cli.md
  - linenoise:
    - Introduction: Redis-cli/linenoise/index.md
- Memory-management:
  - Introduction: Memory-management/index.md
  - zmalloc:
    - Introduction: Memory-management/zmalloc/index.md
plugins:
- search
repo_url: https://github.com/dengking/decompose-redis
site_author: DengKing
site_description: Project documentation with Markdown.
site_name: decompose-redis
site_url: https://dengking.github.io/decompose-redis
theme:
  name: material
